name: levy4_25
benchmark: levy4_25
num_iters: 100
num_init: 10
parameters: null
bounds: [[-10, 5], [-10, 10], [-5, 10], [-1, 10], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
noise_std: 0.01